### ISSUE TITLE
我有一个swift和OC混编的项目，同时引入了这个库和swift版flexlayout，会报YGLayout类重复的问题，希望能改进下。

### ISSUE THREAD

**Issue by MQL9011** [guangmingzizai/FlexLayout-OC#1]
```
Class YGLayout is implemented in both
```

**Comment by guangmingzizai** [comment]
To resolve this problem, we have to refactor Swift's FlexLayout: https://gitee.com/guangmingzizai/FlexLayout.
Contact me: guangmingzizai@qq.com.

**Comment by MQL9011** [comment]
To resolve this problem. Can you refactor FlexLayout-OC ?
Maybe rename the YGLayout class.
Please....help.....

**Comment by guangmingzizai** [comment]
> To resolve this problem. Can you refactor FlexLayout-OC ?
> Maybe rename the YGLayout class.
> Please....help.....

The solution is ugly and workload is heavy, we have to modify all symbols of Yoga, if Yoga updates, we must merge manual, I don't think this is a good idea.

**Comment by MQL9011** [comment]
Well, I use 'FileMerge' compared 'YGLayout.mm' in 'Flexlayout' and 'YGLayout.m' in 'GMYogaKit'.
I found the main  is in line 397 round. 
Does this matter ？
![image](https://user-images.githubusercontent.com/11871158/80168565-c1147500-8615-11ea-97a7-1f650cffbba4.png)

**Comment by guangmingzizai** [comment]
> Well, I use 'FileMerge' compared 'YGLayout.mm' in 'Flexlayout' and 'YGLayout.m' in 'GMYogaKit'.
> I found the main is in line 397 round.
> Does this matter ？
> ![image](https://user-images.githubusercontent.com/11871158/80168565-c1147500-8615-11ea-97a7-1f650cffbba4.png)

According to my online practices(DAU hundreds of thousands), did not find.
The space name of github is my wechat name, you can contact me.
